name: ğŸŒ Deploy to VPS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: ğŸ”’ Checkout code
              uses: actions/checkout@v4

            - name: âœ‰ï¸ Run deploy commands on VPS
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  port: ${{ secrets.SSH_PORT }}
                  key: ${{ secrets.SSH_SECRET_KEY }}
                  script: |
                      cd /home/apps/zyrohub
                      pm2 stop ZyroHub
                      git pull
                      bun install
                      bun run build
                      pm2 start ZyroHub
